/*******************************************************************************

    consent-rr - cookie-consent resource replacements for uBlock Origin
    Copyright (C) 2026-present ryanbr
    SPDX-License-Identifier: GPL-3.0-or-later

    Bundles src/*.js into dist/consent-rr.txt, the resources file format that
    uBlock Origin's hidden setting "userResourcesLocation" fetches.

    That format is line-based and unforgiving (see uBO's
    RedirectEngine.resourcesFromString):
      - a blank line ENDS the current resource, so the code cannot contain one
      - a line starting with "// " or "#" is DROPPED, comments included
      - a line starting with "/// " is a directive, never code
    So every resource is stripped of blank lines and whole-line comments here,
    and the result is checked before it ships.

    User-supplied resources have no web-accessible URL, so uBO serves them as
    data:text/javascript;base64,... built with btoa() - which throws on any
    character above U+00FF. Non-ASCII is rejected for that reason.

*/

import { strict as assert } from 'node:assert';
import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import * as vm from 'node:vm';

const root = path.join(import.meta.dirname, '..');
const srcDir = path.join(root, 'src');
const outFile = path.join(root, 'dist', 'consent-rr.txt');

const reInclude = /^\s*\/\/\s*@include\s+(\S+)\s*$/;

/******************************************************************************/

// Drops blank lines, whole-line "//" comments and whole-line block comments.
// Line-based, so a source file may not carry a template literal: a stripped
// line inside one would change the string. Guarded against below.

const compact = text => {
    const out = [];
    let inBlock = false;
    for ( const line of text.split('\n') ) {
        const trimmed = line.trim();
        if ( inBlock ) {
            if ( trimmed.endsWith('*/') ) { inBlock = false; }
            continue;
        }
        if ( trimmed === '' ) { continue; }
        if ( trimmed.startsWith('//') ) { continue; }
        if ( trimmed.startsWith('/*') ) {
            if ( trimmed.endsWith('*/') === false ) { inBlock = true; }
            continue;
        }
        out.push(line);
    }
    return out;
};

const resolveIncludes = async (file, seen = new Set()) => {
    assert.ok(seen.has(file) === false, `include cycle at ${file}`);
    seen.add(file);
    const text = await fs.readFile(file, 'utf8');
    assert.ok(
        text.includes('`') === false,
        `${path.relative(root, file)}: template literals are not supported, ` +
        `the bundler strips lines`
    );
    const lines = [];
    for ( const line of text.split('\n') ) {
        const match = reInclude.exec(line);
        if ( match === null ) {
            lines.push(line);
            continue;
        }
        const included = path.resolve(path.dirname(file), match[1]);
        lines.push(...await resolveIncludes(included, seen));
    }
    return lines;
};

/******************************************************************************/

const build = async ( ) => {
    const names = (await fs.readdir(srcDir))
        .filter(name => name.endsWith('.js'))
        .sort();
    assert.ok(names.length !== 0, 'no resources found in src/');

    const entries = [];
    for ( const name of names ) {
        const lines = compact(
            (await resolveIncludes(path.join(srcDir, name))).join('\n')
        );
        const code = lines.join('\n');

        // Everything uBO's parser would choke on, before it ships.
        for ( const line of lines ) {
            assert.ok(
                line.startsWith('/// ') === false,
                `${name}: a code line may not start with "/// "`
            );
            assert.ok(
                line.startsWith('#') === false,
                `${name}: a code line may not start with "#"`
            );
        }
        const nonAscii = /[^\x20-\x7e\t\n]/.exec(code);
        assert.ok(
            nonAscii === null,
            `${name}: non-ASCII character ${JSON.stringify(nonAscii && nonAscii[0])} ` +
            `would break uBO's btoa() encoding`
        );
        new vm.Script(code, { filename: name });

        entries.push({ name, code });
        console.log(`  ${name}: ${lines.length} lines, ${code.length} bytes`);
    }

    const header = [
        '# consent-rr - cookie-consent resource replacements for uBlock Origin',
        '# https://github.com/ryanbr/consent-rr',
        '#',
        '# Generated by tools/build.mjs - edit src/, not this file.',
        '#',
        '# Install: uBlock Origin -> Settings -> Advanced settings ->',
        '# userResourcesLocation, set to the raw URL of this file, then reload',
        '# the filter lists.',
        '',
    ].join('\n');

    const body = entries.map(entry => `/// ${entry.name}\n${entry.code}\n`);
    await fs.writeFile(outFile, `${header}${body.join('\n')}`, 'utf8');
    console.log(`\nwrote ${path.relative(root, outFile)}`);
};

await build();
